let handler = async (m, { conn,text }) => {
    let buru = `"kamado_nezuko",
    "iu_v35",
    "Velvia1",
    "koreanDollLikeness_v20",
    "fashionGirl_v55",
    "ahegaoRollingEyes_v11",
    "breastinclassbetter_v141",
    "yaeMikoMix",
    "godPussy1_v3",
    "japaneseDollLikeness_v15",
    "sam_yang",
    "onOff_v3",
    "mix4",
    "epiNoiseoffset_v2",
    "AiGirlFace2",
    "miku_nakano",
    "irene_v70",
    "makima_offset",
    "alice_nikke",
    "russianDollLikeness_v3",
    "ganyu_offset",
    "hutao_offset",
    "march7th_hsr_offset",
    "POV_Doggystyle_LoRA_1MB",
    "POVDoggy",
    "redoOfPovbjer_v3",
    "shirtliftv1",
    "PovDoggyAnal-v3",
    "komi_shouko",
    "uber-realistic-merge",
    "turanga_leela",
    "onArmorMeatShield_v1",
    "shojo_vibe_v1.1",
    "jokowi",
    "film_velvia_2",
    "3d_render_mm",
    "jinxlol_v1",
    "niji_v2",
    "shirtlift",
    "skirtlift",
    "nami_offset",
    "hinata_offset",
    "kaguyaN_offset",
    "keqing_offset",
    "roxy_migurdia_offset",
    "more_details",
    "obsidian_skin",
    "frieren",
    "sasuke_bortod",
    "albedo_overlord",
    "indonesiaDollLikeness",
    "constricted_pupils",
    "kafka_hsr",
    "GrantGustinNextToOliverQueensGraveMeme",
    "heart_star_pupils",
    "slingshot_swimsuit",
    "yor_briar",
    "shanijkt48",
    "add_details",
    "kitagawa_marin",
    "hoshino_ai",
    "re4ashley",
    "bondage",
    "after_sex",
    "kebaya_bali",
    "missionary_vc",
    "beautifulEyesLikeness",
    "hentai_xray",
    "handpull",
    "cameltoe",
    "lora_3dmm_v12",
    "animetarotV51",
    "colorwater_v4",
    "anime_minimalist_v1",
    "blindbox_v1_mix",
    "MoXinV1",
    "pepe_frog",
    "CuteCreatures",
    "oversized_coat",
    "drawing_style",
    "dark_theme"`
if (text) {
    global.db.data.chats[m.chat].lora_model = text
    m.reply(`✅ Lora_model set ${text}`)
  } else throw `✳️ Enter the Model From List of models ${buru}\n@user (mention)`
}
handler.help = ['setlora <text>']
handler.tags = ['ai']
handler.command = ['setlora','loramodel','lora'] 
export default handler